// <auto-generated />
using InMemoryCaching.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InMemoryCaching.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240928071531_initialize_db")]
    partial class initialize_db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("InMemoryCaching.Database.Categories", b =>
                {
                    b.Property<int>("catId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("catName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("catId");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            catId = 1,
                            catName = "Burgers 0"
                        },
                        new
                        {
                            catId = 2,
                            catName = "Burgers 1"
                        },
                        new
                        {
                            catId = 3,
                            catName = "Burgers 2"
                        },
                        new
                        {
                            catId = 4,
                            catName = "Burgers 3"
                        },
                        new
                        {
                            catId = 5,
                            catName = "Burgers 4"
                        },
                        new
                        {
                            catId = 6,
                            catName = "Burgers 5"
                        },
                        new
                        {
                            catId = 7,
                            catName = "Burgers 6"
                        },
                        new
                        {
                            catId = 8,
                            catName = "Burgers 7"
                        },
                        new
                        {
                            catId = 9,
                            catName = "Burgers 8"
                        },
                        new
                        {
                            catId = 10,
                            catName = "Burgers 9"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
