// <auto-generated />
using EfCoreTips.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfCoreTips.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240928062110_insert_Tables")]
    partial class insert_Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("EfCoreTips.Database.Entities.Categories", b =>
                {
                    b.Property<int>("catId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("catName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("catId");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            catId = 1,
                            catName = "Burgers"
                        },
                        new
                        {
                            catId = 2,
                            catName = "Pizza"
                        },
                        new
                        {
                            catId = 3,
                            catName = "Pasta"
                        },
                        new
                        {
                            catId = 4,
                            catName = "Drinks"
                        });
                });

            modelBuilder.Entity("EfCoreTips.Database.Entities.Products", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("catId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("productId");

                    b.HasIndex("catId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            productId = 1,
                            catId = 2,
                            isActive = true,
                            productName = "Product 0"
                        },
                        new
                        {
                            productId = 2,
                            catId = 2,
                            isActive = false,
                            productName = "Product 1"
                        },
                        new
                        {
                            productId = 3,
                            catId = 2,
                            isActive = true,
                            productName = "Product 2"
                        },
                        new
                        {
                            productId = 4,
                            catId = 2,
                            isActive = false,
                            productName = "Product 3"
                        },
                        new
                        {
                            productId = 5,
                            catId = 2,
                            isActive = true,
                            productName = "Product 4"
                        },
                        new
                        {
                            productId = 6,
                            catId = 2,
                            isActive = false,
                            productName = "Product 5"
                        },
                        new
                        {
                            productId = 7,
                            catId = 2,
                            isActive = true,
                            productName = "Product 6"
                        },
                        new
                        {
                            productId = 8,
                            catId = 2,
                            isActive = false,
                            productName = "Product 7"
                        },
                        new
                        {
                            productId = 9,
                            catId = 2,
                            isActive = true,
                            productName = "Product 8"
                        },
                        new
                        {
                            productId = 10,
                            catId = 2,
                            isActive = false,
                            productName = "Product 9"
                        },
                        new
                        {
                            productId = 11,
                            catId = 2,
                            isActive = true,
                            productName = "Product 10"
                        },
                        new
                        {
                            productId = 12,
                            catId = 2,
                            isActive = false,
                            productName = "Product 11"
                        },
                        new
                        {
                            productId = 13,
                            catId = 2,
                            isActive = true,
                            productName = "Product 12"
                        },
                        new
                        {
                            productId = 14,
                            catId = 2,
                            isActive = false,
                            productName = "Product 13"
                        },
                        new
                        {
                            productId = 15,
                            catId = 2,
                            isActive = true,
                            productName = "Product 14"
                        },
                        new
                        {
                            productId = 16,
                            catId = 2,
                            isActive = false,
                            productName = "Product 15"
                        },
                        new
                        {
                            productId = 17,
                            catId = 2,
                            isActive = true,
                            productName = "Product 16"
                        },
                        new
                        {
                            productId = 18,
                            catId = 2,
                            isActive = false,
                            productName = "Product 17"
                        },
                        new
                        {
                            productId = 19,
                            catId = 2,
                            isActive = true,
                            productName = "Product 18"
                        },
                        new
                        {
                            productId = 20,
                            catId = 2,
                            isActive = false,
                            productName = "Product 19"
                        },
                        new
                        {
                            productId = 21,
                            catId = 2,
                            isActive = true,
                            productName = "Product 20"
                        },
                        new
                        {
                            productId = 22,
                            catId = 2,
                            isActive = false,
                            productName = "Product 21"
                        },
                        new
                        {
                            productId = 23,
                            catId = 2,
                            isActive = true,
                            productName = "Product 22"
                        },
                        new
                        {
                            productId = 24,
                            catId = 2,
                            isActive = false,
                            productName = "Product 23"
                        },
                        new
                        {
                            productId = 25,
                            catId = 2,
                            isActive = true,
                            productName = "Product 24"
                        },
                        new
                        {
                            productId = 26,
                            catId = 2,
                            isActive = false,
                            productName = "Product 25"
                        },
                        new
                        {
                            productId = 27,
                            catId = 2,
                            isActive = true,
                            productName = "Product 26"
                        },
                        new
                        {
                            productId = 28,
                            catId = 2,
                            isActive = false,
                            productName = "Product 27"
                        },
                        new
                        {
                            productId = 29,
                            catId = 2,
                            isActive = true,
                            productName = "Product 28"
                        },
                        new
                        {
                            productId = 30,
                            catId = 2,
                            isActive = false,
                            productName = "Product 29"
                        },
                        new
                        {
                            productId = 31,
                            catId = 2,
                            isActive = true,
                            productName = "Product 30"
                        },
                        new
                        {
                            productId = 32,
                            catId = 2,
                            isActive = false,
                            productName = "Product 31"
                        },
                        new
                        {
                            productId = 33,
                            catId = 2,
                            isActive = true,
                            productName = "Product 32"
                        },
                        new
                        {
                            productId = 34,
                            catId = 2,
                            isActive = false,
                            productName = "Product 33"
                        },
                        new
                        {
                            productId = 35,
                            catId = 2,
                            isActive = true,
                            productName = "Product 34"
                        },
                        new
                        {
                            productId = 36,
                            catId = 2,
                            isActive = false,
                            productName = "Product 35"
                        },
                        new
                        {
                            productId = 37,
                            catId = 2,
                            isActive = true,
                            productName = "Product 36"
                        },
                        new
                        {
                            productId = 38,
                            catId = 2,
                            isActive = false,
                            productName = "Product 37"
                        },
                        new
                        {
                            productId = 39,
                            catId = 2,
                            isActive = true,
                            productName = "Product 38"
                        },
                        new
                        {
                            productId = 40,
                            catId = 2,
                            isActive = false,
                            productName = "Product 39"
                        },
                        new
                        {
                            productId = 41,
                            catId = 2,
                            isActive = true,
                            productName = "Product 40"
                        },
                        new
                        {
                            productId = 42,
                            catId = 2,
                            isActive = false,
                            productName = "Product 41"
                        },
                        new
                        {
                            productId = 43,
                            catId = 2,
                            isActive = true,
                            productName = "Product 42"
                        },
                        new
                        {
                            productId = 44,
                            catId = 2,
                            isActive = false,
                            productName = "Product 43"
                        },
                        new
                        {
                            productId = 45,
                            catId = 2,
                            isActive = true,
                            productName = "Product 44"
                        },
                        new
                        {
                            productId = 46,
                            catId = 2,
                            isActive = false,
                            productName = "Product 45"
                        },
                        new
                        {
                            productId = 47,
                            catId = 2,
                            isActive = true,
                            productName = "Product 46"
                        },
                        new
                        {
                            productId = 48,
                            catId = 2,
                            isActive = false,
                            productName = "Product 47"
                        },
                        new
                        {
                            productId = 49,
                            catId = 2,
                            isActive = true,
                            productName = "Product 48"
                        },
                        new
                        {
                            productId = 50,
                            catId = 2,
                            isActive = false,
                            productName = "Product 49"
                        },
                        new
                        {
                            productId = 51,
                            catId = 2,
                            isActive = true,
                            productName = "Product 50"
                        },
                        new
                        {
                            productId = 52,
                            catId = 2,
                            isActive = false,
                            productName = "Product 51"
                        },
                        new
                        {
                            productId = 53,
                            catId = 2,
                            isActive = true,
                            productName = "Product 52"
                        },
                        new
                        {
                            productId = 54,
                            catId = 2,
                            isActive = false,
                            productName = "Product 53"
                        },
                        new
                        {
                            productId = 55,
                            catId = 2,
                            isActive = true,
                            productName = "Product 54"
                        },
                        new
                        {
                            productId = 56,
                            catId = 2,
                            isActive = false,
                            productName = "Product 55"
                        },
                        new
                        {
                            productId = 57,
                            catId = 2,
                            isActive = true,
                            productName = "Product 56"
                        },
                        new
                        {
                            productId = 58,
                            catId = 2,
                            isActive = false,
                            productName = "Product 57"
                        },
                        new
                        {
                            productId = 59,
                            catId = 2,
                            isActive = true,
                            productName = "Product 58"
                        },
                        new
                        {
                            productId = 60,
                            catId = 2,
                            isActive = false,
                            productName = "Product 59"
                        },
                        new
                        {
                            productId = 61,
                            catId = 2,
                            isActive = true,
                            productName = "Product 60"
                        },
                        new
                        {
                            productId = 62,
                            catId = 2,
                            isActive = false,
                            productName = "Product 61"
                        },
                        new
                        {
                            productId = 63,
                            catId = 2,
                            isActive = true,
                            productName = "Product 62"
                        },
                        new
                        {
                            productId = 64,
                            catId = 2,
                            isActive = false,
                            productName = "Product 63"
                        },
                        new
                        {
                            productId = 65,
                            catId = 2,
                            isActive = true,
                            productName = "Product 64"
                        },
                        new
                        {
                            productId = 66,
                            catId = 2,
                            isActive = false,
                            productName = "Product 65"
                        },
                        new
                        {
                            productId = 67,
                            catId = 2,
                            isActive = true,
                            productName = "Product 66"
                        },
                        new
                        {
                            productId = 68,
                            catId = 2,
                            isActive = false,
                            productName = "Product 67"
                        },
                        new
                        {
                            productId = 69,
                            catId = 2,
                            isActive = true,
                            productName = "Product 68"
                        },
                        new
                        {
                            productId = 70,
                            catId = 2,
                            isActive = false,
                            productName = "Product 69"
                        },
                        new
                        {
                            productId = 71,
                            catId = 2,
                            isActive = true,
                            productName = "Product 70"
                        },
                        new
                        {
                            productId = 72,
                            catId = 2,
                            isActive = false,
                            productName = "Product 71"
                        },
                        new
                        {
                            productId = 73,
                            catId = 2,
                            isActive = true,
                            productName = "Product 72"
                        },
                        new
                        {
                            productId = 74,
                            catId = 2,
                            isActive = false,
                            productName = "Product 73"
                        },
                        new
                        {
                            productId = 75,
                            catId = 2,
                            isActive = true,
                            productName = "Product 74"
                        },
                        new
                        {
                            productId = 76,
                            catId = 2,
                            isActive = false,
                            productName = "Product 75"
                        },
                        new
                        {
                            productId = 77,
                            catId = 2,
                            isActive = true,
                            productName = "Product 76"
                        },
                        new
                        {
                            productId = 78,
                            catId = 2,
                            isActive = false,
                            productName = "Product 77"
                        },
                        new
                        {
                            productId = 79,
                            catId = 2,
                            isActive = true,
                            productName = "Product 78"
                        },
                        new
                        {
                            productId = 80,
                            catId = 2,
                            isActive = false,
                            productName = "Product 79"
                        },
                        new
                        {
                            productId = 81,
                            catId = 2,
                            isActive = true,
                            productName = "Product 80"
                        },
                        new
                        {
                            productId = 82,
                            catId = 2,
                            isActive = false,
                            productName = "Product 81"
                        },
                        new
                        {
                            productId = 83,
                            catId = 2,
                            isActive = true,
                            productName = "Product 82"
                        },
                        new
                        {
                            productId = 84,
                            catId = 2,
                            isActive = false,
                            productName = "Product 83"
                        },
                        new
                        {
                            productId = 85,
                            catId = 2,
                            isActive = true,
                            productName = "Product 84"
                        },
                        new
                        {
                            productId = 86,
                            catId = 2,
                            isActive = false,
                            productName = "Product 85"
                        },
                        new
                        {
                            productId = 87,
                            catId = 2,
                            isActive = true,
                            productName = "Product 86"
                        },
                        new
                        {
                            productId = 88,
                            catId = 2,
                            isActive = false,
                            productName = "Product 87"
                        },
                        new
                        {
                            productId = 89,
                            catId = 2,
                            isActive = true,
                            productName = "Product 88"
                        },
                        new
                        {
                            productId = 90,
                            catId = 2,
                            isActive = false,
                            productName = "Product 89"
                        });
                });

            modelBuilder.Entity("EfCoreTips.Database.Entities.Products", b =>
                {
                    b.HasOne("EfCoreTips.Database.Entities.Categories", "categories")
                        .WithMany("products")
                        .HasForeignKey("catId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categories");
                });

            modelBuilder.Entity("EfCoreTips.Database.Entities.Categories", b =>
                {
                    b.Navigation("products");
                });
#pragma warning restore 612, 618
        }
    }
}
