// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultipleDatabases.Database;

#nullable disable

namespace MultipleDatabases.Migrations.Restaurant
{
    [DbContext(typeof(RestaurantContext))]
    [Migration("20240928065903_initialize_db")]
    partial class initialize_db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("MultipleDatabases.Database.Entities.Categories", b =>
                {
                    b.Property<int>("catId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("catName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("catId");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            catId = 1,
                            catName = "Burgers"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
