version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"  # Map host port 5000 to container port 8080
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "eLvisH@9699clear"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
